const {
    Client, ITEMS_HANDLING_FLAGS, SERVER_PACKET_TYPE, LocationsManager, ReceivedItemsPacket,
    clientStatuses,
    itemsHandlingFlags
} = require("archipelago.js");
const Alpine = require('alpinejs').default;
const $ = require('jquery')
const SaveData = require("./savedata.js");
const {GameSave, getFile, getFileList, openDatabase} = SaveData;
const {config} = require("config")
const {genres, genreInfo} = require("./genres.js")

document.addEventListener("alpine:init", onInit)

let puzzleframe;
let apReady = false;

/**
 * @type{import("archipelago.js").JSONRecord}
 */
let slotData;

/**
 * @type{Client}
 */
let client;

let remoteSolved = {};

// Fallback used only when a Keen puzzle's slot-data-declared digit group
// count is unavailable (e.g. Freeplay/debug mode, where there's no
// Archipelago world dictating one).
const DEFAULT_DIGIT_GROUP_COUNT = 10;

/**
 * Per-puzzle digit_group_count targets, from slotData.digit_group_counts
 * (index = puzzle index - 1). Populated at connect time.
 * @type {number[]}
 */
let digitGroupCounts = [];

/**
 * Resolved when the next `js_update_permalinks` fires, with the freshly
 * reported "<params>:<full-descriptor>" game id. Used by
 * ArchipelagoPuzzle#resolveContent() to capture the true, fully-revealed
 * descriptor for a Keen puzzle generated by seed, without any WASM/native
 * changes -- this is the same callback the permalink UI already relies on.
 * @type {((gameId: string) => void)|null}
 */
let pendingGameIdResolve = null;

function waitForNextGameId() {
    return new Promise((resolve) => { pendingGameIdResolve = resolve; });
}

/**
 * Resolved when the next `getForcedCellsCallback` fires, with the result
 * string from getForcedCells() below.
 * @type {((result: string) => void)|null}
 */
let pendingForcedCellsResolve = null;

function waitForForcedCells() {
    return new Promise((resolve) => { pendingForcedCellsResolve = resolve; });
}

function getForcedCellsCallback(result) {
    if (pendingForcedCellsResolve) {
        const resolve = pendingForcedCellsResolve;
        pendingForcedCellsResolve = null;
        resolve(result);
    }
}

/**
 * Queries the real Keen solver -- running in the shared puzzleframe's
 * currently-loaded WASM module, via the get_forced_cells_for_desc/
 * free_forced_cells native export added for this -- for which cells are
 * uniquely forced by a partial set of visible clues. This is the actual
 * solving logic from ap-sgtpuzzles (keen.c's solver()), not a
 * reimplementation, so its results are exactly what the real game engine
 * would deduce.
 *
 * descStr should be a full Keen descriptor ("<cell-and-cage-structure>,
 * <clues>" as produced by the WASM module itself) with any cages not yet
 * meant to be revealed encoded as 'n' (no clue) -- see keen.c's
 * C_NO_CLUE / encode_clues. paramsStr is the plain "<w>d<e|m>"-style
 * params string (no genre prefix, no seed/id suffix).
 *
 * Requires a Keen puzzle to already be loaded into the shared puzzleframe
 * (i.e. loadPuzzle("keen") must have run) -- only one puzzle's WASM module
 * is ever loaded into it at a time, matching every other cross-frame call
 * in this file. Only one call may be in flight at once, for the same
 * reason resolveContent() serializes on resolvingEntry.
 *
 * @param {string} paramsStr
 * @param {string} descStr
 * @returns {Promise<string>} a string of paramsStr's w*w cells, one char
 *   each in the puzzle's row-major order: a digit for a forced cell, '.'
 *   for one not yet determined. Empty string if descStr doesn't validate
 *   against paramsStr.
 */
function getForcedCells(paramsStr, descStr) {
    const resultPromise = waitForForcedCells();
    sendMessage("getForcedCells", paramsStr, descStr);
    return resultPromise;
}

// ---------------------------------------------------------------------
// Keen descriptor parsing/construction (formerly keenDescriptor.js).
//
// Parsing and stage-descriptor construction for Keen puzzle description
// strings, as produced/consumed by Simon Tatham's Portable Puzzle
// Collection's `keen.c` (see `encode_block_structure` / `parse_block_structure`
// / `new_game_desc` / `validate_desc`). This does NOT reimplement any
// puzzle-solving logic -- it only knows how to turn a Keen descriptor
// string into a structured {cages} list, and how to turn that back into a
// *partial* descriptor string with some cages' clues masked out as 'n'
// (Keen's legitimate "no clue" marker), for progressive reveal.
//
// Descriptor format (the part after the ':' in a full puzzle id
// "<params>:<description>"):
//
//   <block-structure-encoding>,<per-cage-clue>*
// ---------------------------------------------------------------------

/**
 * Union-find where the representative ("find") of any set is always its
 * minimum member -- this matches Simon Tatham's `dsf_new_min` semantics,
 * which `keen.c` relies on to determine cage enumeration order (cages are
 * emitted, and their clues read back, in order of increasing minimum cell
 * index).
 */
class MinDSF {
    constructor(n) {
        this.parent = new Int32Array(n);
        for (let i = 0; i < n; i++) this.parent[i] = i;
    }

    find(x) {
        let root = x;
        while (this.parent[root] !== root) root = this.parent[root];
        while (this.parent[x] !== root) {
            const next = this.parent[x];
            this.parent[x] = root;
            x = next;
        }
        return root;
    }

    merge(a, b) {
        let ra = this.find(a);
        let rb = this.find(b);
        if (ra === rb) return;
        if (ra < rb) {
            this.parent[rb] = ra;
        } else {
            this.parent[ra] = rb;
        }
    }
}

/**
 * Port of keen.c's parse_block_structure(). Consumes characters from `str`
 * starting at `pos` until (but not including) the first ',' outside of a
 * repeat-count run, merging cells in `dsf` accordingly.
 *
 * @returns {{dsf: MinDSF, endPos: number}} endPos points at the ',' (or end
 *   of string, though a valid descriptor always has the comma).
 */
function parseBlockStructure(gridWidth, str, pos) {
    const a = gridWidth * gridWidth;
    const dsf = new MinDSF(a);
    const wallSlots = 2 * gridWidth * (gridWidth - 1);

    let i = pos;
    let slotPos = 0;
    let repc = 0;
    let repn = 0;

    while (i < str.length && (repn > 0 || str[i] !== ',')) {
        let c;
        if (repn > 0) {
            repn--;
            c = repc;
        } else if (str[i] === '_' || (str[i] >= 'a' && str[i] <= 'z')) {
            c = str[i] === '_' ? 0 : str.charCodeAt(i) - 'a'.charCodeAt(0) + 1;
            i++;
            let numStr = '';
            while (i < str.length && str[i] >= '0' && str[i] <= '9') {
                numStr += str[i];
                i++;
            }
            if (numStr) {
                repc = c;
                repn = parseInt(numStr, 10) - 1;
            }
        } else {
            throw new Error(`Invalid character in game description at offset ${i}`);
        }

        const adv = c !== 25; // 'z' is a special case: 25 non-walls, no following wall

        while (c-- > 0) {
            if (slotPos >= wallSlots) {
                throw new Error('Too much data in block structure specification');
            }
            let p0, p1;
            if (slotPos < gridWidth * (gridWidth - 1)) {
                const y = Math.floor(slotPos / (gridWidth - 1));
                const x = slotPos % (gridWidth - 1);
                p0 = y * gridWidth + x;
                p1 = y * gridWidth + x + 1;
            } else {
                const x = Math.floor(slotPos / (gridWidth - 1)) - gridWidth;
                const y = slotPos % (gridWidth - 1);
                p0 = y * gridWidth + x;
                p1 = (y + 1) * gridWidth + x;
            }
            dsf.merge(p0, p1);
            slotPos++;
        }
        if (adv) {
            slotPos++;
            if (slotPos > wallSlots + 1) {
                throw new Error('Too much data in block structure specification');
            }
        }
    }

    if (slotPos !== wallSlots + 1) {
        throw new Error('Not enough data in block structure specification');
    }

    return { dsf, endPos: i };
}

/**
 * Builds the ordered cage list (cage j = j-th cell, in increasing index
 * order, that is the minimum member of its own equivalence class) from a
 * parsed block-structure DSF. This ordering is exactly the order Keen's
 * clue list is written in/read from.
 */
function cagesFromDsf(dsf, gridWidth) {
    const a = gridWidth * gridWidth;
    const rootToCageIndex = new Map();
    const cages = [];

    for (let i = 0; i < a; i++) {
        if (dsf.find(i) === i) {
            rootToCageIndex.set(i, cages.length);
            cages.push({ cells: [] });
        }
    }

    for (let i = 0; i < a; i++) {
        const cageIdx = rootToCageIndex.get(dsf.find(i));
        cages[cageIdx].cells.push(i);
    }

    return cages;
}

const OP_CHAR_TO_NAME = { a: 'add', s: 'sub', m: 'mul', d: 'div' };

/**
 * Parses the clue list (the part of the descriptor after the comma),
 * expecting exactly `numCages` entries, in order.
 *
 * @returns {{clueTokens: string[], endPos: number}} clueTokens[j] is the
 *   raw source text for cage j's clue (e.g. "a7", "n"), preserved verbatim
 *   so re-emitting an unmodified cage's clue is a byte-for-byte no-op.
 */
function parseClueList(str, pos, numCages) {
    const clueTokens = [];
    let i = pos;

    for (let k = 0; k < numCages; k++) {
        const start = i;
        const opChar = str[i];
        if (opChar === undefined) {
            throw new Error('Too few clues for block structure');
        }
        i++;

        if (opChar !== 'n') {
            if (!(opChar in OP_CHAR_TO_NAME)) {
                throw new Error(`Unrecognised clue type '${opChar}'`);
            }
            while (i < str.length && str[i] >= '0' && str[i] <= '9') i++;
        }

        clueTokens.push(str.slice(start, i));
    }

    if (i < str.length) {
        throw new Error('Too many clues for block structure');
    }

    return { clueTokens, endPos: i };
}

function clueTokenToOpValue(token) {
    if (token === 'n') return { op: 'none', value: null };
    const opChar = token[0];
    const value = parseInt(token.slice(1), 10);
    return { op: OP_CHAR_TO_NAME[opChar], value };
}

/**
 * Parses a full Keen descriptor (the part after the ':' in a puzzle id) into
 * a structured cage list plus the raw pieces needed to reconstruct partial
 * ("some cages hidden") versions of it later.
 *
 * @param {number} gridWidth
 * @param {string} desc - e.g. "a_b3,,a7s2m12..." (block structure, comma,
 *   clue list)
 * @returns {{
 *   cages: {cells: number[], op: string, value: number|null}[],
 *   blockPart: string,       // includes the trailing comma
 *   clueTokens: string[],    // raw per-cage clue text, in cage order
 * }}
 */
function parseKeenDescriptor(gridWidth, desc) {
    const { dsf, endPos: commaPos } = parseBlockStructure(gridWidth, desc, 0);
    if (desc[commaPos] !== ',') {
        throw new Error("Expected ',' after block structure description");
    }
    const blockPart = desc.slice(0, commaPos + 1);

    const cages = cagesFromDsf(dsf, gridWidth);
    const { clueTokens, endPos } = parseClueList(desc, commaPos + 1, cages.length);

    if (endPos !== desc.length) {
        throw new Error('Trailing data after clue list');
    }

    for (let j = 0; j < cages.length; j++) {
        const { op, value } = clueTokenToOpValue(clueTokens[j]);
        if ((op === 'sub' || op === 'div') && cages[j].cells.length !== 2) {
            throw new Error('Subtraction and division cages must have area 2');
        }
        cages[j].op = op;
        cages[j].value = value;
    }

    return { cages, blockPart, clueTokens };
}

/**
 * Extracts the grid width from a Keen params string (e.g. "6de", "9dxm").
 * Mirrors keen.c's decode_params: the width is just the leading digits.
 */
function parseKeenParamsWidth(paramsStr) {
    const match = /^(\d+)/.exec(paramsStr);
    if (!match) throw new Error(`Could not parse grid width from params "${paramsStr}"`);
    return parseInt(match[1], 10);
}

/**
 * Builds a *display* descriptor where every cage not in `activeCageIndices`
 * has its clue masked out as 'n' (Keen's legitimate "no clue" marker,
 * understood natively by the game engine/solver). The block structure
 * (cage shapes) is always fully present -- only which clues are legible
 * changes across stages.
 *
 * @param {string} blockPart - from parseKeenDescriptor
 * @param {string[]} clueTokens - from parseKeenDescriptor (full/true clues)
 * @param {Set<number>|number[]} activeCageIndices
 */
function buildStageDescriptor(blockPart, clueTokens, activeCageIndices) {
    const active = activeCageIndices instanceof Set ? activeCageIndices : new Set(activeCageIndices);
    let clueStr = '';
    for (let j = 0; j < clueTokens.length; j++) {
        clueStr += active.has(j) ? clueTokens[j] : 'n';
    }
    return blockPart + clueStr;
}

/**
 * Convenience wrapper: given a full puzzle id "<params>:<desc>" and the set
 * of cages that should be visible, returns the puzzle id string for that
 * stage.
 */
function buildStagePuzzleId(paramsStr, blockPart, clueTokens, activeCageIndices) {
    return `${paramsStr}:${buildStageDescriptor(blockPart, clueTokens, activeCageIndices)}`;
}

// ---------------------------------------------------------------------
// Keen save-file parsing/reconstruction (formerly keenSaveFile.js).
//
// Parser/reconstructor for the save-file format produced by
// `get_save_file()` (Simon Tatham midend's `midend_serialise`, see
// `midend.c`). This lets us read back the *current* grid contents (which
// definite digits the player has entered so far) purely in JS, with no
// native/WASM changes -- `get_save_file()` is already exposed and callable
// at any time via the existing `savePuzzleData()` message round-trip.
//
// File format (midend.c's midend_serialise): a sequence of lines, each
// `<header>:<byte length of content>:<content>\n`. Relevant headers for our
// purposes:
//   DESC       - the game description in effect for state 0
//   NSTATES    - total number of states ever visited (including redoable
//                "future" ones)
//   STATEPOS   - 1-indexed index of the CURRENT state (states[statepos-1])
//   MOVE/SOLVE/RESTART - one per state transition (i=1..nstates-1, in
//                order), giving the move string that produced state i from
//                state i-1
//
// Only the transitions up to (and not past) STATEPOS are part of the
// current grid -- anything after that is only reachable via redo.
// ---------------------------------------------------------------------

/**
 * Splits raw save-file text into {header, content} records, per the
 * `<header>:<len>:<content>\n` framing. Uses the declared byte length
 * rather than splitting on newlines, since content is allowed to contain
 * anything (including newlines) as long as the length matches.
 */
function parseRecords(text) {
    const records = [];
    let pos = 0;
    const n = text.length;

    while (pos < n) {
        // Skip a lone trailing newline/whitespace at EOF.
        if (text.slice(pos).trim() === '') break;

        const firstColon = text.indexOf(':', pos);
        if (firstColon === -1) throw new Error(`Malformed save file: missing ':' after header at offset ${pos}`);
        const header = text.slice(pos, firstColon).trim();

        const secondColon = text.indexOf(':', firstColon + 1);
        if (secondColon === -1) throw new Error(`Malformed save file: missing length field for header "${header}"`);
        const lenStr = text.slice(firstColon + 1, secondColon);
        const len = parseInt(lenStr, 10);
        if (!Number.isFinite(len) || len < 0) {
            throw new Error(`Malformed save file: bad length "${lenStr}" for header "${header}"`);
        }

        const contentStart = secondColon + 1;
        const contentEnd = contentStart + len;
        if (contentEnd > n) throw new Error(`Malformed save file: declared length ${len} for "${header}" exceeds remaining data`);
        const content = text.slice(contentStart, contentEnd);

        // Expect (and skip) the trailing newline, if present.
        let next = contentEnd;
        if (text[next] === '\n') next++;
        else if (text[next] === '\r' && text[next + 1] === '\n') next += 2;

        records.push({ header, content });
        pos = next;
    }

    return records;
}

/**
 * Parses a Keen (or generically, any Simon Tatham puzzle) save file into
 * its structured fields.
 *
 * @returns {{
 *   desc: string|null,
 *   nstates: number,
 *   statepos: number,
 *   transitions: {type: 'MOVE'|'SOLVE'|'RESTART', str: string}[],
 * }}
 */
function parseSaveFile(text) {
    const records = parseRecords(text);

    let desc = null;
    let nstates = null;
    let statepos = null;
    const transitions = [];

    for (const { header, content } of records) {
        switch (header) {
            case 'DESC':
                desc = content;
                break;
            case 'NSTATES':
                nstates = parseInt(content, 10);
                break;
            case 'STATEPOS':
                statepos = parseInt(content, 10);
                break;
            case 'MOVE':
                transitions.push({ type: 'MOVE', str: content });
                break;
            case 'SOLVE':
                transitions.push({ type: 'SOLVE', str: content });
                break;
            case 'RESTART':
                transitions.push({ type: 'RESTART', str: content });
                break;
            default:
                // Ignore everything else (SAVEFILE, VERSION, GAME, PARAMS,
                // CPARAMS, SEED/HEXSEED, PRIVDESC, AUXINFO, UI, TIME, ...) --
                // not needed to reconstruct the grid.
                break;
        }
    }

    if (nstates === null) throw new Error('Save file missing NSTATES');
    if (statepos === null) throw new Error('Save file missing STATEPOS');
    if (statepos < 1 || statepos > nstates) {
        throw new Error(`Save file has out-of-range STATEPOS ${statepos} (NSTATES ${nstates})`);
    }
    if (transitions.length !== nstates - 1) {
        throw new Error(
            `Save file has ${transitions.length} move transitions but NSTATES=${nstates} implies ${nstates - 1}`
        );
    }

    return { desc, nstates, statepos, transitions };
}

/**
 * Applies a single 'MOVE'-type move string (Keen's `interpret_move` output:
 * "R<x>,<y>,<n>" for a definite-digit entry, "P<x>,<y>,<n>" for a pencil
 * mark) to a mutable grid array. Pencil marks don't affect the definite
 * grid and are ignored here.
 */
function applyKeenMoveString(grid, gridWidth, moveStr) {
    const kind = moveStr[0];
    if (kind !== 'R' && kind !== 'P') return; // unrecognised move kind; ignore defensively

    const rest = moveStr.slice(1);
    const parts = rest.split(',');
    if (parts.length !== 3) throw new Error(`Malformed Keen move string "${moveStr}"`);
    const x = parseInt(parts[0], 10);
    const y = parseInt(parts[1], 10);
    const n = parseInt(parts[2], 10);

    if (kind === 'R') {
        if (x < 0 || x >= gridWidth || y < 0 || y >= gridWidth) {
            throw new Error(`Move string "${moveStr}" out of bounds for width ${gridWidth}`);
        }
        grid[y * gridWidth + x] = n; // n === 0 means "cleared"
    }
    // 'P' (pencil) moves don't change definite digits.
}

/**
 * Applies a 'SOLVE'-type move string. Keen's solve() aux data (and hence
 * the move string used to apply a full solve) is "S" followed by exactly
 * w*w digit characters, one per cell in row-major order.
 */
function applyKeenSolveString(grid, gridWidth, moveStr) {
    if (moveStr[0] !== 'S') throw new Error(`Malformed Keen solve string "${moveStr}"`);
    const digits = moveStr.slice(1);
    if (digits.length !== gridWidth * gridWidth) {
        throw new Error(`Solve string has ${digits.length} digits, expected ${gridWidth * gridWidth}`);
    }
    for (let i = 0; i < digits.length; i++) {
        grid[i] = digits.charCodeAt(i) - '0'.charCodeAt(0);
    }
}

/**
 * Reconstructs the current (as of STATEPOS) definite-digit grid for a Keen
 * puzzle from a parsed save file. Cells with no definite digit entered are
 * 0.
 *
 * @param {number} gridWidth
 * @param {ReturnType<typeof parseSaveFile>} parsed
 * @returns {number[]} grid, row-major, length gridWidth*gridWidth
 */
function reconstructKeenGrid(gridWidth, parsed) {
    const a = gridWidth * gridWidth;
    const grid = new Array(a).fill(0);

    // Only transitions up to (not including) STATEPOS are "current" --
    // transitions.length === nstates - 1, and transitions[k] is the move
    // that produced state k+1 from state k. States 0..statepos-1 are
    // applied, i.e. transitions[0 .. statepos-2].
    const appliedCount = parsed.statepos - 1;

    for (let k = 0; k < appliedCount; k++) {
        const { type, str } = parsed.transitions[k];
        if (type === 'MOVE') {
            applyKeenMoveString(grid, gridWidth, str);
        } else if (type === 'SOLVE') {
            applyKeenSolveString(grid, gridWidth, str);
        } else if (type === 'RESTART') {
            grid.fill(0);
        }
    }

    return grid;
}

/**
 * Rewrites a save file's DESC record to a new descriptor string, leaving
 * every other record's content byte-for-byte as it was. Used when
 * advancing a Keen puzzle to a new clue-group stage: the cage shapes and
 * the player's moves never change across stages, only which clues are
 * legible, so an existing save can carry straight over onto the new
 * stage's descriptor.
 *
 * IMPORTANT: unlike parseRecords() above (which locates the header by
 * scanning for the first ':' and so tolerates either form), the real
 * midend's deserialiser (midend_deserialise_internal in midend.c) does NOT
 * scan for a colon at all -- it reads a fixed 9-byte field and requires
 * byte 9 (index 8) to literally be ':'. So every header must be written
 * left-justified and padded with spaces to exactly 8 characters (matching
 * midend_serialise's own `wr` macro / copy_left_justified) or a save
 * rewritten here will fail to load back into the real engine.
 *
 * Descriptor strings are always plain ASCII (digits/letters/punctuation),
 * so string length and byte length coincide here, matching the assumption
 * already made throughout this save-file handling.
 *
 * @param {string} saveText - raw text from get_save_file()/a stored save
 * @param {string} newDesc - the new stage's descriptor (no "<params>:" prefix)
 * @returns {string} the rewritten save file text
 */
function rewriteSaveFileDesc(saveText, newDesc) {
    const records = parseRecords(saveText);

    let found = false;
    let out = '';
    for (const { header, content } of records) {
        const paddedHeader = header.padEnd(8, ' ');
        if (header === 'DESC') {
            found = true;
            out += `${paddedHeader}:${newDesc.length}:${newDesc}\n`;
        } else {
            out += `${paddedHeader}:${content.length}:${content}\n`;
        }
    }

    if (!found) throw new Error('Save file has no DESC record');

    return out;
}

// ---------------------------------------------------------------------
// Progressive clue-group planning, built on the real Keen solver
// (formerly keenSolver.js + keenProgression.js).
//
// Given a puzzle's true full descriptor, works out an ordered sequence of
// clue-group stages: stage k's cages, once visible (along with every
// earlier stage's), make a new set of cells uniquely forced according to
// the actual game engine's own solver (queried via getForcedCells(), see
// above) -- never a local reimplementation of Keen's arithmetic/logic.
// ---------------------------------------------------------------------

/**
 * Queries the real solver for exactly the cells forced when only
 * `activeCageIndices`' clues are visible (every other cage masked as 'n').
 *
 * @returns {Promise<Map<number,number>>} cellIndex -> forced digit
 */
async function forcedCellsForActiveCages(paramsStr, blockPart, clueTokens, activeCageIndices) {
    const descStr = buildStageDescriptor(blockPart, clueTokens, activeCageIndices);
    const resultStr = await getForcedCells(paramsStr, descStr);

    const forced = new Map();
    for (let i = 0; i < resultStr.length; i++) {
        const ch = resultStr[i];
        if (ch !== '.') forced.set(i, ch.charCodeAt(0) - '0'.charCodeAt(0));
    }
    return forced;
}

/**
 * Lazily yields every k-element combination of arr's elements, in
 * lexicographic (by position) order. Generator rather than a materialized
 * array so a caller that stops early (see findMinimalAddition's per-level
 * candidate cap below) never pays for combinations it never looks at --
 * this matters once arr.length gets into the dozens, where C(n,3) can run
 * into the thousands.
 */
function* combosOf(arr, k) {
    const combo = [];
    function* rec(start) {
        if (combo.length === k) { yield [...combo]; return; }
        for (let i = start; i < arr.length; i++) {
            combo.push(arr[i]);
            yield* rec(i + 1);
            combo.pop();
        }
    }
    yield* rec(0);
}

// Cap on how many same-size combinations findMinimalAddition will probe
// before giving up on that combo size and escalating. Without this, a
// large grid (9x9+, several dozen cages) can make the brute-force
// combination search combinatorially expensive: C(30,3) is already 4060
// real-solver queries, each a cross-iframe round trip. Combined with
// ordering candidates by cage size (below), this keeps each stage's
// planning bounded and fast in practice while still trying a substantial
// number of candidates before falling back.
const MAX_CANDIDATES_PER_LEVEL = 100;

/**
 * Finds a combination of not-yet-active cages that, when added, the real
 * solver forces at least one new cell from. Escalates combo size from 1 up
 * to maxComboSize; if nothing up to that size makes progress, falls back
 * to activating everything remaining at once (this always makes progress
 * against a puzzle that's fully solvable by the real solver with all
 * clues present).
 *
 * Within a given combo size, this returns the FIRST combination found to
 * make progress rather than exhaustively searching for the one with the
 * fewest newly forced cells -- for a large cage count, finding the true
 * minimum would mean probing every combination even after already finding
 * a perfectly good one. To make that first hit come early (and keep
 * average-case cost low), candidates are tried smallest-cage-first: a
 * smaller cage (especially a 2-cell subtraction/division cage, which is
 * tightly constrained) is far more likely to be independently forced than
 * a large one, so trying those first tends to resolve at k=1 well before
 * the combo search would otherwise need to escalate.
 *
 * Calls are made one at a time (awaited in sequence, never in parallel) --
 * only one query may be in flight against the shared iframe's WASM module
 * at once, same as every other cross-frame call in this file.
 *
 * @param {{cells: number[]}[]} cages - full cage list (for size ordering)
 * @returns {Promise<{cageIndices:number[], newlyForced: Map<number,number>}>}
 */
async function findMinimalAddition(paramsStr, blockPart, clueTokens, activeSet, remaining, known, cages, maxComboSize) {
    const remainingArr = [...remaining].sort(
        (a, b) => cages[a].cells.length - cages[b].cells.length || a - b);

    for (let k = 1; k <= Math.min(maxComboSize, remainingArr.length); k++) {
        let tried = 0;
        for (const combo of combosOf(remainingArr, k)) {
            if (tried++ >= MAX_CANDIDATES_PER_LEVEL) break;

            const activeIndices = [...activeSet, ...combo];
            const forced = await forcedCellsForActiveCages(paramsStr, blockPart, clueTokens, activeIndices);
            const newlyForced = new Map();
            for (const [cell, value] of forced) {
                if (!known.has(cell)) newlyForced.set(cell, value);
            }
            if (newlyForced.size > 0) {
                return { cageIndices: combo, newlyForced };
            }
        }
    }

    // Fallback: activate everything remaining at once.
    const activeIndices = [...activeSet, ...remainingArr];
    const forced = await forcedCellsForActiveCages(paramsStr, blockPart, clueTokens, activeIndices);
    const newlyForced = new Map();
    for (const [cell, value] of forced) {
        if (!known.has(cell)) newlyForced.set(cell, value);
    }
    return { cageIndices: remainingArr, newlyForced };
}

/**
 * Builds the finest-grained (natural) ordering of a puzzle's cages into
 * stages, greedily picking the smallest addition that makes progress (per
 * the real solver) at each step. This is the "maximize the length of the
 * progression" search.
 *
 * @returns {Promise<{cageIndices:number[], newlyForced: Map<number,number>}[]>}
 *   stages, in reveal order. Concatenating all stages' cageIndices covers
 *   every cage exactly once, and all stages' newlyForced maps together
 *   cover the whole grid (the puzzle is fully solved once every stage is
 *   active) -- assuming the puzzle is solvable by the real solver at all.
 */
async function planNaturalStages(paramsStr, blockPart, clueTokens, cages, maxComboSize) {
    let active = new Set();
    let remaining = new Set();
    for (let i = 0; i < cages.length; i++) remaining.add(i);
    let known = new Map();
    const stages = [];

    while (remaining.size > 0) {
        const found = await findMinimalAddition(paramsStr, blockPart, clueTokens, active, remaining, known, cages, maxComboSize);
        for (const idx of found.cageIndices) {
            active.add(idx);
            remaining.delete(idx);
        }
        for (const [cell, value] of found.newlyForced) known.set(cell, value);

        if (found.newlyForced.size === 0) {
            // These cages turned out to be logically redundant given
            // everything already known (their information was already
            // implied). Don't give them their own empty stage -- fold them
            // into the previous one so every stage still represents real
            // progress. If this is the very first stage, the puzzle can't
            // be solved by the real solver at all (without guessing).
            if (stages.length === 0) {
                throw new Error('Puzzle is not solvable by the real solver without guessing.');
            }
            stages[stages.length - 1].cageIndices.push(...found.cageIndices);
        } else {
            stages.push(found);
        }
    }

    return stages;
}

/**
 * Merges adjacent stages (always the pair with the fewest combined newly
 * forced cells, to keep the remaining stages as evenly sized as possible)
 * until exactly `target` stages remain. Returns null if `stages` already
 * has fewer than `target` entries -- the caller should fall back to
 * clamping, or (during generation) pick a different seed/larger grid.
 */
function mergeToTargetCount(stages, target) {
    if (stages.length < target) return null;
    if (target < 1) throw new Error('target must be >= 1');

    let result = stages.map((s) => ({
        cageIndices: [...s.cageIndices],
        newlyForced: new Map(s.newlyForced),
    }));

    while (result.length > target) {
        let bestIdx = 0;
        let bestSize = Infinity;
        for (let i = 0; i < result.length - 1; i++) {
            const size = result[i].newlyForced.size + result[i + 1].newlyForced.size;
            if (size < bestSize) { bestSize = size; bestIdx = i; }
        }
        const merged = {
            cageIndices: [...result[bestIdx].cageIndices, ...result[bestIdx + 1].cageIndices],
            newlyForced: new Map([...result[bestIdx].newlyForced, ...result[bestIdx + 1].newlyForced]),
        };
        result.splice(bestIdx, 2, merged);
    }

    return result;
}

/**
 * End-to-end: plan the natural stage decomposition for a puzzle (via the
 * real solver) and merge it down to `targetGroupCount` stages. If the
 * puzzle's natural chain is shorter than the target -- a small/simple grid
 * can end up fully forced from very little visible information -- falls
 * back to the natural decomposition as-is (fewer, coarser stages than
 * requested) rather than failing the puzzle outright. The caller doesn't
 * need to special-case a short result: newlyCompletedStages() already
 * treats any digit-group index beyond the actual stage count as completed
 * once the whole grid is filled in, so no location becomes permanently
 * unreachable.
 */
async function planClueGroups(paramsStr, blockPart, clueTokens, cages, targetGroupCount, maxComboSize) {
    const natural = await planNaturalStages(paramsStr, blockPart, clueTokens, cages, maxComboSize);
    const merged = mergeToTargetCount(natural, targetGroupCount);
    if (merged) return merged;

    console.warn(
        `Keen puzzle only naturally decomposes into ${natural.length} clue group(s) ` +
        `(requested ${targetGroupCount}) -- using ${natural.length} instead. Any ` +
        `additional configured digit groups will complete together with the final one.`
    );
    return natural;
}

/**
 * Resolves a Keen puzzle's static content (cages, solution, clue-group
 * stages) from its true full descriptor (obtained once via a by-seed or
 * by-id generation pass) and a target digit-group count, using the real
 * Keen solver (via getForcedCells()) for every solving step.
 *
 * @param {string} paramsStr - e.g. "6de"
 * @param {string} fullDescriptor - the ":"-suffix of a full "<params>:<desc>"
 *   puzzle id, i.e. just the "<desc>" part, with every cage's real clue
 *   visible (as freshly generated -- never partially masked).
 * @param {number} digitGroupCount - target number of stages (from slot
 *   data's `digit_group_counts[i]`)
 * @param {number} [maxComboSize]
 * @returns {Promise<{
 *   w: number,
 *   cages: object[],
 *   blockPart: string,
 *   clueTokens: string[],
 *   solution: number[],   // row-major, length w*w
 *   stages: object[],     // from planClueGroups, length digitGroupCount
 * }>}
 */
async function resolveKeenPuzzle(paramsStr, fullDescriptor, digitGroupCount, maxComboSize = 3) {
    const w = parseKeenParamsWidth(paramsStr);
    const { cages, blockPart, clueTokens } = parseKeenDescriptor(w, fullDescriptor);

    const allIndices = cages.map((_, i) => i);
    const solutionMap = await forcedCellsForActiveCages(paramsStr, blockPart, clueTokens, allIndices);
    if (solutionMap.size !== w * w) {
        throw new Error(
            `Puzzle is not fully solvable by the real solver (${solutionMap.size}/${w * w} cells) ` +
            `-- bad seed or unsupported difficulty.`
        );
    }
    const solution = new Array(w * w);
    for (const [cell, value] of solutionMap) solution[cell] = value;

    const stages = await planClueGroups(paramsStr, blockPart, clueTokens, cages, digitGroupCount, maxComboSize);

    return { w, cages, blockPart, clueTokens, solution, stages };
}

/**
 * Cages visible (i.e. NOT masked as 'n') once `clueSetCount` copies of the
 * Clue Set item have been received: stages[0..clueSetCount-1]'s cages,
 * cumulative. clueSetCount 0 => nothing visible (blank puzzle).
 */
function activeCageIndicesForCount(stages, clueSetCount) {
    const active = new Set();
    const n = Math.max(0, Math.min(clueSetCount, stages.length));
    for (let k = 0; k < n; k++) {
        for (const c of stages[k].cageIndices) active.add(c);
    }
    return active;
}

/**
 * Builds the puzzle id string ("<params>:<descriptor>") for the puzzle as
 * it should appear once `clueSetCount` Clue Set items have been received.
 */
function buildStagePuzzleIdForCount(paramsStr, resolved, clueSetCount) {
    const active = activeCageIndicesForCount(resolved.stages, clueSetCount);
    return buildStagePuzzleId(paramsStr, resolved.blockPart, resolved.clueTokens, active);
}

/**
 * Given the player's currently-entered grid (0 = blank, matching Keen's own
 * convention) and a resolved puzzle, returns the list of stage indices
 * (0-indexed; "Digit Group stageIndex+1") whose target cells are ALL
 * correctly filled, restricted to indices reachable at `clueSetCount` (i.e.
 * index < clueSetCount) and not already in `alreadyChecked`.
 *
 * `resolved.stages.length` can be smaller than the configured
 * digit_group_count (see planClueGroups()'s clamp fallback, for a
 * small/simple grid whose natural decomposition is shorter than requested).
 * Any index at or beyond that length has no cage-specific cells of its own
 * to check -- by construction, every real stage's newlyForced maps together
 * already cover the whole grid -- so it's treated as completed once the
 * entire grid matches the puzzle's solution, same moment as the final real
 * stage. This keeps every configured Digit Group location reachable even
 * when the puzzle itself only has fewer natural stages.
 *
 * @param {object} resolved - from resolveKeenPuzzle
 * @param {number[]} enteredGrid - row-major, length w*w
 * @param {number} clueSetCount
 * @param {Set<number>} alreadyChecked - stage indices already checked; not
 *   mutated
 * @returns {number[]} newly-completed stage indices, in ascending order
 */
function newlyCompletedStages(resolved, enteredGrid, clueSetCount, alreadyChecked) {
    const completed = [];
    const totalStages = resolved.stages.length;
    if (totalStages === 0) return completed;

    for (let k = 0; k < clueSetCount; k++) {
        if (alreadyChecked.has(k)) continue;

        let allMatch = true;
        if (k < totalStages) {
            for (const [cell, value] of resolved.stages[k].newlyForced) {
                if (enteredGrid[cell] !== value) {
                    allMatch = false;
                    break;
                }
            }
        } else {
            for (let cell = 0; cell < resolved.solution.length; cell++) {
                if (enteredGrid[cell] !== resolved.solution[cell]) {
                    allMatch = false;
                    break;
                }
            }
        }
        if (allMatch) completed.push(k);
    }
    return completed;
}

/**
 * Only one puzzle's content may be resolved (which requires actually
 * driving the shared puzzleframe through a throwaway by-seed generation
 * pass) at a time. While set, puzzle switching is briefly held off to avoid
 * two overlapping loads racing on the same iframe.
 * @type {ArchipelagoPuzzle|null}
 */
let resolvingEntry = null;

class ArchipelagoPuzzle {
    constructor(options) {
        // Puzzle genre
        this.genre = options.genre;

        // Puzzle generation options (size, difficulty, etc.)
        this.params = options.params;

        // Human-readable puzzle description
        this.desc = "";

        // Puzzle number; also Archipelago region/item number
        this.index = options.index;

        // Puzzle id (params:data)
        this.puzzleId = options.puzzleId;

        // Puzzle seed (genParams#seed)
        this.puzzleSeed = options.puzzleSeed;

        this.solved = options.solved ?? false;
        this.collected = options.collected ?? false;
        this.locked = options.locked ?? false;
        this.item = options.item;
        this.state = "";

        // -- Progressive Keen ("Clue Set" item / "Digit Group" location) state --

        // Target number of clue-group stages for this puzzle, from
        // slotData.digit_group_counts[index-1] (set by loadFileData()).
        this.digitGroupCount = options.digitGroupCount ?? DEFAULT_DIGIT_GROUP_COUNT;

        // Number of "Puzzle {index} Clue Set" item copies received so far.
        // Recomputed from client.items.received on every syncAPStatus().
        this.clueSetCount = 0;

        // 0-indexed stage numbers (stage k == "Digit Group k+1") whose
        // location has already been checked, per client.room.checkedLocations.
        // Recomputed on every syncAPStatus().
        this.checkedStages = new Set();

        // Resolved puzzle content (cages/solution/stages), computed once per
        // puzzle via a throwaway by-seed generation pass. See resolveContent().
        this.resolved = null;
        this.paramsStr = null;
        this._resolvingPromise = null;

        this.updateDescription();
        this.updateState();
    }

    /**
     * Resolves this puzzle's true content (cages, solution, clue-group
     * stages) by generating it once from its seed. Idempotent -- safe to
     * call repeatedly; only does real work the first time. Does NOT itself
     * navigate to the correct current-stage descriptor afterwards -- call
     * reloadAtCurrentStage() for that (selectPuzzle() does both).
     *
     * This briefly drives the shared puzzleframe through a hidden
     * full-reveal load in order to capture the freshly generated
     * "<params>:<descriptor>" game id (via js_update_permalinks), which is
     * the only way to learn a Keen puzzle's true cages/clues without
     * duplicating the WASM generator in JS.
     */
    async resolveContent() {
        if (this.resolved) return this.resolved;
        if (this._resolvingPromise) return this._resolvingPromise;

        this._resolvingPromise = (async () => {
            // Briefly drive the shared puzzleframe through a hidden load of
            // this puzzle -- whether it's only known by seed (in which case
            // this is also how its true full descriptor is captured, via
            // js_update_permalinks) or already known by exact id. Either
            // way the "keen" WASM module needs to actually be loaded there
            // before the getForcedCells() real-solver calls below (inside
            // resolveKeenPuzzle) have anything to talk to, and it needs to
            // STAY loaded (hence wrapping the whole computation, not just
            // this load, in the hidden/resolvingEntry guard) for every one
            // of those calls, not just the first.
            resolvingEntry = this;
            const previousVisibility = puzzleframe.style.visibility;
            puzzleframe.style.visibility = "hidden";
            try {
                const gameIdPromise = waitForNextGameId();
                await loadPuzzle(this.genre, this.puzzleId ?? this.puzzleSeed, true, undefined);
                const gameId = await gameIdPromise;

                const colonIdx = gameId.indexOf(":");
                if (colonIdx === -1) {
                    throw new Error(`Unexpected game id with no descriptor: "${gameId}"`);
                }
                this.paramsStr = gameId.slice(0, colonIdx);
                const fullDescriptor = gameId.slice(colonIdx + 1);

                this.resolved = await resolveKeenPuzzle(
                    this.paramsStr, fullDescriptor, this.digitGroupCount);
            } finally {
                puzzleframe.style.visibility = previousVisibility;
                resolvingEntry = null;
                this._resolvingPromise = null;
            }
            return this.resolved;
        })();

        return this._resolvingPromise;
    }

    /**
     * (Re)loads this puzzle in the shared puzzleframe at the descriptor
     * matching its current clueSetCount, replaying any existing move data
     * (via the normal save/load-on-js_post_init path) against it. No-op if
     * resolveContent() hasn't completed yet.
     *
     * If a save already exists for this puzzle, its embedded DESC record
     * (from whatever stage it was last saved at) is rewritten to the
     * current stage's descriptor first -- otherwise loadPuzzle()'s "don't
     * bother sending an id if a save exists" shortcut would cause
     * js_post_init's automatic loadPuzzleData() to reconstruct the puzzle
     * at its *old*, stale stage instead. The cage shapes never change
     * across stages (only which clues are visible), and Keen's move format
     * doesn't depend on clue visibility, so the player's entered digits
     * carry over exactly.
     */
    async reloadAtCurrentStage() {
        if (!this.resolved) return;
        this.puzzleId = buildStagePuzzleIdForCount(
            this.paramsStr, this.resolved, this.clueSetCount);
        const stageDescOnly = this.puzzleId.slice(this.paramsStr.length + 1);

        const gamesaves = Alpine.store("gamesaves");
        if (gamesaves.current) {
            const existingSave = await gamesaves.current.getPuzzleSave(this.index);
            if (existingSave) {
                try {
                    const rewritten = rewriteSaveFileDesc(existingSave, stageDescOnly);
                    await gamesaves.current.setPuzzleSave(this.index, rewritten);
                } catch (e) {
                    console.warn(`Discarding unreadable save for puzzle ${this.index}:`, e);
                    await gamesaves.current.deletePuzzleSave(this.index);
                }
            }
        }

        await loadPuzzle(this.genre, this.puzzleId, true, this.index);
    }

    /**
     * Checks the player's currently-entered digits (reconstructed from a
     * `get_save_file()` round trip) against each
     * not-yet-checked, currently-reachable digit group's target cells, and
     * calls client.check() for any that are now fully and correctly filled.
     *
     * @param {string} saveFileText - raw text from get_save_file(), as
     *   delivered to savePuzzleDataCallback()
     */
    checkStageCompletion(saveFileText) {
        if (!this.resolved || !isApReady()) return;

        let grid;
        try {
            const parsed = parseSaveFile(saveFileText);
            grid = reconstructKeenGrid(this.resolved.w, parsed);
        } catch (e) {
            console.warn("Failed to parse save file for stage completion check:", e);
            return;
        }

        const newlyCompleted = newlyCompletedStages(
            this.resolved, grid, this.clueSetCount, this.checkedStages);

        for (const stageIdx of newlyCompleted) {
            this.checkedStages.add(stageIdx);
            const locationName = `Puzzle ${this.index} Digit Group ${stageIdx + 1}`;
            const locationId = locationNameToId(locationName);
            if (locationId !== undefined && locationId !== null) {
                client.check(locationId);
            } else {
                console.warn(`No location id found for "${locationName}"`);
            }
        }

        if (newlyCompleted.length > 0 && this.checkedStages.size >= this.digitGroupCount && !this.solved) {
            this.solved = true;
            this.updateState();
            Alpine.store("puzzleList").resort();
        }
    }

    updateDescription() {
        let name = genreInfo[this.genre].name;

        if (this.params) {
            this.desc = `${name}: ${this.params}`;
        } else {
            this.desc = name;
        }
    }

    updateState() {
        if (this.locked) {
            this.state = "locked";
        } else if (this.solved) {
            this.state = "solved";
        } else {
            this.state = "unlocked";
        }
    }

    onSolve() {
        // For progressive Keen puzzles there's no single "Reward" location
        // any more -- each digit group is its own location, and those are
        // checked incrementally by checkStageCompletion() (triggered on
        // every move via js_update_status). Native onSolve only fires once
        // the whole grid is filled and fully constraint-satisfied, which
        // for a progressive puzzle only happens once every clue is visible
        // (the final stage) -- so treat it as a redundant nudge to check
        // one more time, rather than a distinct completion path.
        if (this.genre === "keen") {
            if (this.resolved && isApReady()) {
                savePuzzleData();
            }
            return;
        }

        this.solved = true;
        this.updateState();

        if (isApReady()) {
            let locationId = locationNameToId(`Puzzle ${this.index} Reward`);

            client.check(locationId);
        }
    }

    static fromArchipelagoString(genreAndParams, baseSeed, index, options) {
        options ??= {};

        const archipelagoStringRegex = /^(?<genre>[^:\n]*)(:(?<params>[^:#\n]*)((?<separator>[:#])?(?<seedOrId>.*)))?$/
        let genreParamsMatch = archipelagoStringRegex.exec(genreAndParams);

        let genre = genreParamsMatch.groups.genre;
        let params = genreParamsMatch.groups.params;
        let separator = genreParamsMatch.groups.separator;
        let seedOrId = genreParamsMatch.groups.seedOrId;

        options.genre = genre;
        options.params = params;
        options.index = index;

        if (separator == ":") {
            options.puzzleId = `${params}:${seedOrId}`;
        } else if (separator == "#") {
            options.puzzleSeed = `${params}#${seedOrId}`;
        } else {
            // Auto-generate seed
            let seedPrefix = ""+index;
            seedPrefix = seedPrefix.padStart(3, "0");
            let seed = `${seedPrefix}${baseSeed}`;
            options.puzzleSeed = `${params}#${seed}`;
        }

        return new ArchipelagoPuzzle(options);
    }

    static fromPuzzlesString(genre, seedOrId, index, options) {
        options ??= {};

        if (seedOrId) {
            let paramsSeparatorMatch = /^([^:#]*)([:#]?)/.exec(seedOrId);

            options.params = paramsSeparatorMatch[1];
            let separator = paramsSeparatorMatch[2];

            if (separator == ":") {
                options.puzzleId = seedOrId;
            } else {
                // also treat string with no separator as seed
                options.puzzleSeed = seedOrId;
            }
        } else {
            options.params = "";
        }

        options.index ??= index;
        options.genre = genre;

        return new ArchipelagoPuzzle(options);
    }
}

function sendMessage(command, ...args) {
    if (puzzleframe) {
        puzzleframe.contentWindow.postMessage([command, ...args])
    }
}

function onInit() {
    console.log("puzzles.html: onInit")

    async function initSaveData() {
        await openDatabase()
        console.log("Savedata open")
        await loadFileList()
        console.log("File list loaded")
    }

    initSaveData();

    initStores()

    // Set up puzzleframe
    puzzleframe = document.getElementById("puzzleframe");

    // puzzleframe will send ["ready"] when initialization is done
}

/**
 * First-time initialization for puzzle data Alpine stores.
 */
function initStores() {
    // List of available puzzles from Archipelago
    Alpine.store("puzzleList", {
        entries: [],
        sortedEntries: [],
        currentIndex: -1,
        current: null,
        solveCount: 0,
        solveTarget: null,
        finished: false,
        sortBySolved: false,
        selectPuzzle(entry) {
            if (!entry) {
                this.currentIndex = -1;
                this.current = null;
                return;
            }

            // Avoid two overlapping loads racing on the single shared
            // puzzleframe while a puzzle's content is being resolved.
            if (resolvingEntry && resolvingEntry !== entry) {
                return;
            }

            if (entry.index == this.currentIndex) {
                return;
            }

            this.currentIndex = entry.index;
            this.current = entry;

            if (entry.genre === "keen" && isApReady()) {
                entry.resolveContent().then(() => entry.reloadAtCurrentStage());
            } else if (entry.puzzleId) {
                loadPuzzle(entry.genre, entry.puzzleId, true, entry.index);
            } else if (entry.puzzleSeed) {
                loadPuzzle(entry.genre, entry.puzzleSeed, true, entry.index);
            } else {
                loadPuzzle(entry.genre, "", false);
            }
        },
        markSolved(puzzle) {
            puzzle ??= this.current

            if (puzzle) {
                puzzle.onSolve();

                if (puzzle == this.current) {
                    savePuzzleData();
                }

                const gamesaves = Alpine.store("gamesaves")

                if (puzzle.index && gamesaves.current) {
                    gamesaves.current.puzzleSolved[puzzle.index-1] = true;
                    gamesaves.current.save();
                    syncAPStatus();
                }

                this.resort();
            }
        },
        resort() {
            // Helper comparison function
            // 0 if a == b; -1 if a < b; 1 if a > b
            // Can be chained with ||
            // Note: this sorts "false" before "true"
            function compare(a,b) {
                if (a < b) return -1;
                else if (a > b) return 1;
                else return 0;
            }

            function sortKey(entry) {
                if (entry.solved) return 1;
                else if (entry.locked) return 2;
                else return 0;
            }

            var sortedEntries = this.entries.slice();
            
            if (this.sortBySolved) {
                sortedEntries.sort((a,b) => compare(sortKey(a), sortKey(b)) || compare(a.id, b.id))
            } else {
                sortedEntries.sort((a,b) => compare(a.id, b.id))
            }

            this.sortedEntries = sortedEntries;

            this.solveCount = this.entries.reduce((a,b) => (b.solved ? a+1 : a), 0)
        },
        onFinishClick() {
            if (this.solveTarget !== null && this.solveCount >= this.solveTarget) {
                client.updateStatus(clientStatuses.goal);
                this.finished = true;
                Alpine.store("gamesaves").markFinished();
            }
        }
    })

    Alpine.store("puzzleList").resort();

    // Various information about the current puzzle
    Alpine.store("puzzleState", {
        onSolve() {
            this.solved = true;
        },
        undoEnabled: false,
        redoEnabled: false,
        solveEnabled: true,
        primaryKeyLabel: "",
        secondaryKeyLabel: "",
        loaded: false,
        solved: false,
        status: 0,
        genre: null,
        genreInfo: genreInfo["none"],
        gameId: "",
        gameSeed: "",
        reset() {
            this.solved = false;
            this.undoEnabled = false;
            this.redoEnabled = false;
            this.solveEnabled = true;
            this.primaryKeyLabel = "";
            this.secondaryKeyLabel = "";
            this.loaded = false;
            this.solved = false;
            this.status = 0;
            this.genre = null;
            this.genreInfo = genreInfo["none"];
            this.gameId = "";
            this.gameSeed = "";
        }
    })

    // A variable to store whether the current puzzle should be played as a fixed puzzle
    // (i.e. disable the Solve button and new game shortcuts)
    Alpine.store("singleMode", false)

    // List of presets for the current puzzle
    // [{id: Int, name: String}]
    Alpine.store("puzzlePresets", [])

    // Dialog box displayed by puzzle midend
    Alpine.store("puzzleDialog", {
        controls: [],
        visible: false,
        addControl(index, type, title, initialValue, choices) {
            if (type == "choice") {
                this.controls.push({index, type, title, value: initialValue, choices})
            } else {
                this.controls.push({index, type, title, value: initialValue})
            }
        },
        confirm: dialogConfirm,
        cancel: dialogCancel,
        dismiss() {
            this.controls = [];
            this.visible = false;
        }
    })

    // Error message displayed by puzzle midend
    Alpine.store("errorMessage", {
        message: "",
        visible: false,
        show(message) {
            this.message = message;
            this.visible = true;
        },
        dismiss() {
            this.visible = false;
        }
    })

    // Puzzle status bar
    Alpine.store("status", {
        message: "",
        visible: false,
        set(value) {
            this.message = value;
            this.visible = true;
        },
        hide() {
            this.message = "";
            this.visible = false;
        }
    })

    // Chat box
    Alpine.store("chatbox", {
        collapsed: true,
        unreadCount: 0,
        composeText: "",
        messages: [],
        messageCount: 0,
        toggleCollapsed() {
            this.collapsed = !this.collapsed;

            if (!this.collapsed) {
                this.scrollToBottom(true)
            }
        },
        appendMessage(message) {
            message.id = this.messageCount++;

            this.messages.push(message)

            const messageLimit = 1000;

            if (this.messages.length > messageLimit) {
                this.messages = this.messages.slice(this.messages.length - messageLimit)
            }

            // TODO: separate notification for priority messages?
            // if (message.highlight || message.type == 'chat') {
            //     this.unreadCount++;
            // }
            this.unreadCount++;
            this.scrollToBottom(false)
        },
        scrollToBottom(force) {
            let isPinned = false;

            if (force) {
                isPinned = true;
            } else {
                let elem = $("#chat-history");
                if (elem.length == 0) return;

                // Check if we are scrolled to the bottom
                const scrollPinHeight = 10
                if (elem.scrollTop() + elem.innerHeight() >= elem[0].scrollHeight - scrollPinHeight) {
                    isPinned = true;
                }
            }

            if (isPinned) {
                this.unreadCount = 0;

                // Wait until next tick so any new messages can render
                Alpine.nextTick(() => {
                    let elem = $("#chat-history");
                    elem.scrollTop(elem[0].scrollHeight);
                })
            }
        },
        appendEcho(text) {
            this.appendMessage({type: 'echo', data: [{text: text}], highlight: false})
        },
        sendChat(text) {
            sendChat(text)
            this.scrollToBottom(true)
            this.composeText = "";
        }
    })

    // Widget to load puzzles on-demand
    // TODO make this with proper UI
    Alpine.store("debugLoader", {
        genre: "net",
        id: "",
        singleMode: false,
        showUnsupported: false,
        load() {
            Alpine.store("puzzleList").selectPuzzle(null);
            loadPuzzle(this.genre, this.id, this.singleMode);
        }
    })

    Alpine.store("connectionInfo", {
        hostname: config.defaultHost,
        port: "38281",
        player: "Player1",
        password: "",
        connect() {
            createFile(this.hostname, +this.port, this.player, this.password);
        },
        replaceConnectionInfo() {
            let currentFile = Alpine.store("gamesaves").current;
            let newConnection = {
                host: this.hostname,
                port: +this.port,
                player: this.player,
                password: this.password
            }
            if (currentFile && currentFile.id != -1) {
                loadFile(currentFile, false, newConnection)
            }
        }
    })

    // TODO a lot of this should be moved to connectionInfo (possibly all of it)
    Alpine.store("gamesaves", {
        list: [],
        current: null,
        apError: false,
        connecting: false,
        connected: false,
        loadFile(file, secretMode) {
            loadFile(file, secretMode);
        },
        deleteFile(file) {
            // TODO proper confirmation dialog
            if (confirm(`${file.toString()}: Delete this file?`)) {
                deleteFile(file)
            }
        },
        markFinished() {
            if (this.current) {
                this.current.finished = true;
                this.current.save();
            }
        }
    })

    Alpine.store("genres", genres)

    Alpine.store("config", config)

    resetPuzzleMetadata();
}

/**
 * Reset all puzzle metadata when loading a new puzzle.
 */
function resetPuzzleMetadata() {
    Alpine.store("puzzleState").reset();
    Alpine.store("puzzlePresets", []);
    Alpine.store("puzzleDialog").dismiss();
    Alpine.store("status").hide();
    Alpine.store("errorMessage").dismiss();
}

async function loadPuzzle(genre, id, singleMode, saveKey) {
    let debugLoader = Alpine.store("debugLoader");
    let puzzleState = Alpine.store("puzzleState");

    if (!genre) {
        id = undefined;
        singleMode = true;
    }

    resetPuzzleMetadata();
    debugLoader.genre = genre;
    debugLoader.id = id;
    debugLoader.singleMode = !!singleMode;
    puzzleState.genre = genre;
    puzzleState.genreInfo = genreInfo[genre || "none"];

    Alpine.store("singleMode", !!singleMode)

    const puzzleFrameBase = "puzzleframe.html";

    const gamesaves = Alpine.store("gamesaves");

    let hasSave = false;

    if (gamesaves.current && saveKey !== null && saveKey !== undefined) {
        let saveData = await gamesaves.current.getPuzzleSave(saveKey);
        if (saveData) {
            hasSave = true;
        }
    }

    let queryFragments = [];

    if (genre) {
        queryFragments.push({key: "g", value: genre});
    }
    // Don't bother sending ID if save data exists
    if (id && !hasSave) {
        queryFragments.push({key: "i", value: id});
    }
    if (singleMode || !genre) {
        queryFragments.push({key: "s", value: "true"});
    }

    let queryString = queryFragments.map(e => `${e.key}=${encodeURIComponent(e.value)}`).join("&");

    puzzleframe.src = null;
    puzzleframe.src = `${puzzleFrameBase}?${queryString}`;
    puzzleframe.width = 0;
    puzzleframe.height = 0;
}

async function clearPuzzle() {
    return await loadPuzzle("");
}

//
// puzzleFrame message handlers
//

function onPuzzleFrameLoad() {
    console.log("puzzles.html: puzzleframe ready")
}

function js_init_puzzle() {
    
}

function js_post_init() {
    loadPuzzleData();
    Alpine.store("puzzleState").loaded = true;
}

function js_enable_undo_redo(enableUndo, enableRedo) {
    Alpine.store("puzzleState").undoEnabled = !!enableUndo
    Alpine.store("puzzleState").redoEnabled = !!enableRedo
}

function js_remove_solve_button() {
    Alpine.store("puzzleState").solveEnabled = false;
}

function js_update_permalinks(gameId, gameSeed) {
    let puzzleState = Alpine.store("puzzleState");
    puzzleState.gameId = gameId;
    puzzleState.gameSeed = gameSeed;

    if (pendingGameIdResolve) {
        const resolve = pendingGameIdResolve;
        pendingGameIdResolve = null;
        resolve(gameId);
    }
}

function js_update_status(newStatus) {
    let puzzleState = Alpine.store("puzzleState");
    puzzleState.status = newStatus;

    const puzzleList = Alpine.store("puzzleList");
    const entry = puzzleList.current;

    if (entry instanceof ArchipelagoPuzzle && entry.genre === "keen" && entry.resolved && isApReady()) {
        // Progressive Keen puzzles are checked incrementally, per digit
        // group, after every move -- not just on a full native solve.
        // savePuzzleData() round-trips through get_save_file() and calls
        // back into savePuzzleDataCallback(), which does the actual check.
        savePuzzleData();
    } else if (puzzleState.status == 1 && !puzzleState.solved) {
        puzzleState.solved = true
        Alpine.store("puzzleList").markSolved()
    }
}

function js_update_key_labels(pcl, scl) {
    let puzzleState = Alpine.store("puzzleState");
    puzzleState.primaryKeyLabel = pcl;
    puzzleState.secondaryKeyLabel = scl;
}

function js_add_preset(menuId, name, id) {
    let newPreset = {menuId, name, id}
    Alpine.store("puzzlePresets").push(newPreset)
}

function js_add_preset_submenu() {
    // Deal with this later
}

function js_select_preset(id) {
    // idk
}

function js_dialog_init() {
    const dialog = Alpine.store("puzzleDialog");
    dialog.controls = [];
}

function js_dialog_string(index, title, initvalue) {
    Alpine.store("puzzleDialog").addControl(index, "string", title, initvalue)
}

function js_dialog_choices(index, title, choiceStr, initvalue) {
    // Split choiceStr by its first character
    let choices = choiceStr.split(choiceStr[0])
    choices.shift()

    Alpine.store("puzzleDialog").addControl(index, "choice", title, initvalue, choices)
}

function js_dialog_boolean(index, title, initvalue) {
    Alpine.store("puzzleDialog").addControl(index, "boolean", title, !!initvalue)
}

function js_dialog_launch() {
    Alpine.store("puzzleDialog").visible = true;
}

function js_dialog_cleanup() {
    Alpine.store("puzzleDialog").dismiss();
}

function js_canvas_set_statusbar(value) {
    Alpine.store("status").set(value);
}

function js_canvas_remove_statusbar() {
    Alpine.store("status").hide();
}

function js_canvas_set_size(w, h) {
    puzzleframe.width = w / window.devicePixelRatio;
    puzzleframe.height = h / window.devicePixelRatio;
}

function js_focus_canvas() {

}

function js_error_box(message) {
    Alpine.store("errorMessage").show(message)
}

function savePuzzleDataCallback(data) {
    console.log("Save file ready")

    const gamesaves = Alpine.store("gamesaves");
    const puzzleList = Alpine.store("puzzleList");
    if (!gamesaves.current || !puzzleList.current) return;

    gamesaves.current.setPuzzleSave(puzzleList.current.index, data)

    const entry = puzzleList.current;
    if (entry instanceof ArchipelagoPuzzle && entry.genre === "keen" && entry.resolved) {
        entry.checkStageCompletion(data);
    }
}

const messageHandlers = {
    ready: onPuzzleFrameLoad, js_init_puzzle, js_post_init,
    js_update_permalinks, js_enable_undo_redo, js_remove_solve_button, js_update_status, js_update_key_labels,
    js_add_preset, js_add_preset_submenu, js_select_preset,
    js_dialog_init, js_dialog_string, js_dialog_choices, js_dialog_boolean, js_dialog_launch, js_dialog_cleanup,
    js_canvas_set_statusbar, js_canvas_remove_statusbar, js_canvas_set_size, js_error_box, js_focus_canvas,
    savePuzzleDataCallback, getForcedCellsCallback
}

function processMessage(message) {
    if (!message.data[Symbol.iterator]) return;

    let [command, ...args] = message.data

    if (command) {
        let handler = messageHandlers[command]
        if (handler) {
            handler(...args)
        } else {
            console.log("to puzzles.html:", message.data)
            console.warn("No handler found for message", message.data[0])
        }
    }
}

window.onmessage = processMessage

//
// UI functions
//

function showPreferences() {
    sendMessage("showPreferences");
}

function newPuzzle() {
    sendMessage("newPuzzle");
    Alpine.store("puzzleState").solved = false;
}

function puzzleFromId() {
    sendMessage("puzzleFromId")
}

function puzzleFromSeed() {
    sendMessage("puzzleFromSeed")
}

function restartPuzzle() {
    sendMessage("restartPuzzle");
}

function undoPuzzle() {
    sendMessage("undoPuzzle");
}

function redoPuzzle() {
    sendMessage("redoPuzzle");
}

function solvePuzzle() {
    const puzzleList = Alpine.store("puzzleList");
    const entry = puzzleList.current;

    if (entry instanceof ArchipelagoPuzzle && entry.genre === "keen" && isApReady()) {
        // The native Solve function operates on whatever subset of clues is
        // currently visible, which for any non-final stage is deliberately
        // under-constrained (that's the whole point of the progressive
        // reveal) -- it will therefore usually just fail with an error, or
        // in rare cases "solve" a puzzle that still has undiscovered digit
        // groups without going through the normal per-stage checks. Disable
        // it entirely for progressive Keen puzzles rather than risk either.
        Alpine.store("errorMessage").show(
            "Solve is disabled for progressive Keen puzzles -- use logical deduction to reveal each digit group."
        );
        return;
    }

    sendMessage("solvePuzzle");

    // Mark puzzle as solved regardless of whether the puzzle was actually solved

    Alpine.store("puzzleList").markSolved()
}

function setPreset(id) {
    sendMessage("setPreset", id)
}

function dialogConfirm() {
    let dialog = Alpine.store("puzzleDialog");
    for (let elem of dialog.controls) {
        switch (elem.type) {
            case "string":
                sendMessage("dialogReturnString", elem.index, elem.value); break;
            case "choice":
                sendMessage("dialogReturnInt", elem.index, elem.value); break;
            case "boolean":
                sendMessage("dialogReturnInt", elem.index, elem.value ? 1 : 0); break;
        }
    }
    sendMessage("dialogConfirm")
}

function dialogCancel() {
    sendMessage("dialogCancel")
}

function savePuzzleData() {
    sendMessage("savePuzzleData")
}

function setNewGameEnabled(allowNewGame) {
    sendMessage("setNewGameEnabled", allowNewGame)
}

async function loadPuzzleData() {
    const gamesaves = Alpine.store("gamesaves");
    const puzzleList = Alpine.store("puzzleList");
    if (!gamesaves.current || !puzzleList.current) return;

    let data = await gamesaves.current.getPuzzleSave(puzzleList.current.index);

    if (data) {
        sendMessage("loadPuzzleData", data);
    }
}

async function deletePuzzleData(index) {
    const gamesaves = Alpine.store("gamesaves");
    const puzzleList = Alpine.store("puzzleList");

    if (gamesaves.current) {
        index ??= puzzleList.current?.index
    }
    if (index === undefined) return;

    await gamesaves.current.deletePuzzleSave(index);

    return;
}

function hasItem(itemId) {
    return client.items.received.findIndex(e => e.id == itemId) > -1;
}

function syncAPStatus() {
    const puzzleList = Alpine.store("puzzleList");

    if (!isApReady()) {
        puzzleList.resort();
        return;
    };

    const gamesaves = Alpine.store("gamesaves");

    let allSolved = true;
    let currentFile = gamesaves.current;

    let fileDirty = false;

    let newRemoteSolves = {};
    let anyNewRemoteSolves = false;

    for (let entry of puzzleList.entries) {
        let dirty = false;

        if (entry.genre === "keen") {
            // -- Progressive Clue Set item / Digit Group locations --

            const itemId = itemNameToId(`Puzzle ${entry.index} Clue Set`);
            const newClueSetCount = (itemId === undefined || itemId === null) ? 0
                : client.items.received.filter(e => e.id === itemId).length;

            if (newClueSetCount !== entry.clueSetCount) {
                entry.clueSetCount = newClueSetCount;
                entry.locked = (newClueSetCount === 0);
                dirty = true;

                // If this puzzle is currently open and already resolved,
                // capture the player's moves and move it to the new stage.
                if (entry === puzzleList.current && entry.resolved) {
                    savePuzzleData();
                    entry.reloadAtCurrentStage();
                }
            }

            const newCheckedStages = new Set();
            for (let k = 0; k < entry.digitGroupCount; k++) {
                const locationId = locationNameToId(`Puzzle ${entry.index} Digit Group ${k + 1}`);
                if (locationId !== undefined && locationId !== null
                    && client.room.checkedLocations.includes(locationId)) {
                    newCheckedStages.add(k);
                }
            }
            if (newCheckedStages.size !== entry.checkedStages.size) {
                dirty = true;
            }
            entry.checkedStages = newCheckedStages;

            const nowSolved = entry.checkedStages.size >= entry.digitGroupCount;
            if (nowSolved !== entry.solved) {
                entry.solved = nowSolved;
                dirty = true;
            }
            entry.collected = entry.solved;
            if (!entry.solved) allSolved = false;
        } else {
            // Legacy single item/location genres -- this world only ever
            // emits Keen puzzles, but Freeplay/debug mode can still list
            // other genres, so keep the old behavior for those.
            let itemId = itemNameToId(`Puzzle ${entry.index}`);
            let locationId = locationNameToId(`Puzzle ${entry.index} Reward`);

            if (!entry.collected && client.room.checkedLocations.includes(locationId)) {
                entry.collected = true;
                dirty = true;
            } else if (!entry.collected) {
                allSolved = false;
            }

            if (entry.locked && hasItem(itemId)) {
                entry.locked = false;
                dirty = true;

                if (currentFile && currentFile.puzzleLocked[entry.index-1]) {
                    currentFile.puzzleLocked[entry.index-1] = false;
                    fileDirty = true;
                }
            }
        }

        if (dirty) {
            entry.updateState();
        }

        if (entry.solved && !(entry.index in remoteSolved)) {
            newRemoteSolves[entry.index] = 1;
            remoteSolved[entry.index] = 1;
            anyNewRemoteSolves = true;
        }
    }

    if (anyNewRemoteSolves) {
        console.log("newly solved: ", newRemoteSolves)
        let team = client.players.self.team
        let slot = client.players.self.slot
        let key = `sgtkeen_solves_${team}_${slot}`
        client.storage.prepare(key, {})
            .update(newRemoteSolves)
            .commit()
    }

    puzzleList.resort();

    if (fileDirty) {
        currentFile.save();
    }
}

async function createFile(hostname, port, player, password) {
    const gamesaves = Alpine.store("gamesaves")
    gamesaves.connecting = true;

    disconnectAP();

    gamesaves.apError = false;

    try {
        await connectAP(hostname, port, player, password);
    } catch (e) {
        alert("Couldn't connect to Archipelago server.");
        console.error("Couldn't connect to Archipelago server");
        console.error(e);

        gamesaves.apError = true;
        gamesaves.connecting = false;

        return;
    }

    let fileVersion = slotData.file_version ?? 0

    console.log(`file_version = ${slotData.file_version}`)
    console.log(`world_version = ${slotData.world_version}`)

    if (fileVersion > 1) {
        alert(`World is version ${slotData.world_version}, which is not compatible with this web client version. Some features may not work as expected.`)
    }

    let newFile = new GameSave({
        host: hostname,
        port: port,
        player: player,
        password: password,
        puzzles: slotData.puzzles,
        baseSeed: "" + slotData.world_seed,
        solveTarget: slotData.solve_target
    });

    await clearPuzzle();

    loadFileData(newFile);

    await newFile.save();

    apReady = true;
    gamesaves.connecting = false;
    gamesaves.list.push(newFile);
    gamesaves.current = newFile;
    initRemoteSolves();
    syncAPStatus();
}

/**
 * 
 * @param {SaveData.GameSave} file 
 */
async function loadFile(file, secretMode, newConnection) {
    const gamesaves = Alpine.store("gamesaves")
    gamesaves.connecting = true;
    gamesaves.current = file;

    disconnectAP();

    gamesaves.apError = false;
    let connectOk = false;

    let host, port, player, password;

    if (newConnection) {
        host = newConnection.host ?? file.host;
        port = newConnection.port ?? file.port;
        player = newConnection.player ?? file.player;
        password = newConnection.password ?? file.password;
    } else {
        host = file.host;
        port = file.port;
        player = file.player;
        password = file.password;
    }

    if (host) {
        try {
            await connectAP(host, port, player, password);
            connectOk = true;
        } catch (e) {
            if (newConnection) {
                alert("Couldn't connect to Archipelago server. Reload this file to connect with previous information.")
            } else {
                alert("Couldn't connect to Archipelago server. (You can still solve unlocked puzzles on this file.)")
            }
            gamesaves.apError = true;
            console.error(e);
        }
    }

    if (connectOk) {
        // Verify puzzle list and seed match
        function anyMismatch() {
            if (file.baseSeed != "" + slotData.world_seed) return true;
            if (file.puzzles.length != slotData.puzzles.length) return true;

            for (let i = 0; i < file.puzzles.length; i++) {
                if (file.puzzles[i] != slotData.puzzles[i]) return true;
            }

            return false;
        }

        if (anyMismatch()) {
            if (newConnection) {
                alert("The Archipelago server data doesn't match this save file. Reload this file to connect with previous information.")
            } else {
                alert("The Archipelago server data doesn't match this save file. (You can still solve unlocked puzzles.)")
            }
            disconnectAP();
            connectOk = false;
            gamesaves.apError = true;
        }
    }

    if (newConnection && connectOk) {
        file.host = host;
        file.port = port;
        file.player = player;
        file.password = password;

        file.updateDescription();
        file.save();
    }

    await clearPuzzle();

    loadFileData(file, secretMode);

    if (connectOk) {
        apReady = true;
        gamesaves.connected = true;
        initRemoteSolves();
    }

    gamesaves.connecting = false;
    syncAPStatus();
}

async function deleteFile(file) {
    await file.deleteFile();
    
    const gamesaves = Alpine.store("gamesaves");
    const puzzleList = Alpine.store("puzzleList");

    let index = gamesaves.list.indexOf(file);
    if (index > -1) {
        gamesaves.list.splice(index, 1);
    }

    if (gamesaves.current == file) {
        // TODO extract this
        clearPuzzle();
        gamesaves.current = null;
        loadFileData(null);
    }
}

async function loadFileList() {
    const gamesaves = Alpine.store("gamesaves");
    gamesaves.list = await getFileList();

    let defaultGame = new GameSave({
        id: -1,
        filename: "Freeplay",
        puzzles: genres.filter(e => true),
        puzzleLocked: genres.map(e => false)
    });

    gamesaves.list.unshift(defaultGame);

    gamesaves.loadFile(defaultGame);
}

function onReceiveItems(event) {
    if (isApReady()) {
        syncAPStatus();
    }
}

function logEvent(event) {
    console.log(event);
}

/**
 * @param {import("archipelago.js").PrintJSONPacket} event 
 * @deprecated
 */
function onPrintJson(event) {
    function processMessagePart(part) {
        const itemTypes = {0: 'filler', 1: 'progression', 2: 'useful', 4: 'trap'}
        switch (part.type) {
            case "player_id":
                return {text: playerIdToName(+part.text), detail: part.text, type: "player"}
            case "item_id":
                return {text: itemIdToName(+part.text), detail: part.text, type: "item", itemType: itemTypes[part.flags]}
            case "location_id":
                return {text: locationIdToName(+part.text), detail: part.text, type: "location"}
            default: return part
        }
    }

    const chatbox = Alpine.store("chatbox")
    let mySlot = client.players.self.slot;

    let highlight = false
    if (event.item && event.item.player === mySlot) {
        highlight = true;
    }
    if (event.receiving === mySlot) {
        highlight = true;
    }

    const newMessage = {
        type: (event.type ?? 'unknown').toLowerCase(),
        data: event.data.map(processMessagePart),
        highlight: highlight
    }
    chatbox.appendMessage(newMessage)
}

/**
 * @param {string} text
 * @param {import("archipelago.js").MessageNode[]} nodes 
 */
function onMessage(text, nodes) {
    const chatbox = Alpine.store("chatbox")

    let highlight = false

    /**
     * @param {import("archipelago.js").MessageNode} n
     */
    function processNode(n) {
        let result = {type: n.type, text: n.text, itemType: null};

        if (n.type == "item") {
            result.itemType = n.item.progression ? "progression" : n.item.useful ? "useful" : n.item.trap ? "trap" : "filler"
            result.detail = result.itemType
        }

        if (n.type == "player" && n.player.slot == client.players.self.slot && n.player.team == client.players.self.team) {
            highlight = true
        }

        return result;
    }

    // TODO message pretty printing
    const newMessage = {
        type: "message",
        data: nodes.map(processNode),
        highlight: highlight
    }

    chatbox.appendMessage(newMessage)
}

/**
 * @param {import("archipelago.js").SetReplyPacket} event 
 */
function onSetReply(event) {
    let team = client.players.self.team
    let slot = client.players.self.slot
    let key = `sgtkeen_solves_${team}_${slot}`

    if (event.key == key) {
        copyRemoteSolves(event.value)
    }
}

/**
 * @param {import("archipelago.js").RetrievedPacket} event 
 */
function onKeysRetreived(event) {
    let team = client.players.self.team
    let slot = client.players.self.slot
    let key = `sgtkeen_solves_${team}_${slot}`

    console.log("KeysRetrieved", event)
    
    if (event.keys[key]) {
        copyRemoteSolves(event.keys[key])
    }
}

function copyRemoteSolves(solves) {
    console.log(solves)
    let puzzleList = Alpine.store("puzzleList")

    let oldRemoteSolved = {};
    Object.assign(oldRemoteSolved, remoteSolved)

    for (let id in solves) {
        if (!(id in oldRemoteSolved)) {
            console.log(`adding remote solve ${id}`)
            remoteSolved[id] = solves[id];
            puzzleList.markSolved(puzzleList.entries[id-1]);
        }
    }
}

function onDisconnected() {
    if (apReady) {
        Alpine.store("gamesaves").apError = true
    }
    apReady = false;
    console.log("disconnected")

    const chatbox = Alpine.store("chatbox")
    chatbox.appendEcho("Disconnected from Archipelago.")
}

function sendChat(text) {
    const chatbox = Alpine.store("chatbox")

    if (!text) return;

    if (text[0] == "/") {
        return handleSlashCommand(text)
    }

    if (!client || !apReady) {
        chatbox.appendEcho("Not connected to Archipelago.")
        return
    }
    client.messages.say(text)
}

async function handleSlashCommand(text) {
    const chatbox = Alpine.store("chatbox")
    const puzzleList = Alpine.store("puzzleList")

    chatbox.appendEcho(text)

    let parts = text.trim().split(/\s+/)
    let command = parts[0] ?? ""

    if (command == "/debugon") {
        Alpine.store("debugMode", true)
        chatbox.appendEcho("Debug mode enabled.")
    } else if (command  == "/debugoff") {
        Alpine.store("debugMode", false)
        chatbox.appendEcho("Debug mode disabled.")
    } else if (command == "/delete_puzzle_data") {
        if (isNaN(parts[1])) {
            chatbox.appendEcho("Specify a puzzle number.")
            return
        }

        let puzzleIndex = +parts[1]
        let puzzle = puzzleList.entries[puzzleIndex-1];
        if (!puzzle) {
            chatbox.appendEcho("No puzzle with that number.")
            return
        }

        await deletePuzzleData(puzzleIndex)
        chatbox.appendEcho(`Deleted save data for "${puzzle.desc}".`)
    } else if (command == "/set_puzzle_seed") {
        if (isNaN(parts[1])) {
            chatbox.appendEcho("Specify a puzzle number.")
        }

        let puzzleIndex = +parts[1]
        let puzzle = puzzleList.entries[puzzleIndex-1];
        if (!puzzle) {
            chatbox.appendEcho("No puzzle with that number.")
        }

        let newSeed = parts[2] ?? "";

        puzzle.puzzleSeed = newSeed
        puzzle.updateDescription()

        chatbox.appendEcho(`Updated seed for "${puzzle.desc}".`)
    } else if (command == "/solve_collected") {
        let solveCount = 0
        for (let puzzle of puzzleList.entries) {
            if (!puzzle.locked && !puzzle.solved && puzzle.collected) {
                puzzleList.markSolved(puzzle)
                solveCount++;
            }
        }
        chatbox.appendEcho(`${solveCount} puzzle(s) marked solved.`)
    } else if (command == "/show_unsupported") {
        Alpine.store("debugLoader").showUnsupported = true;
        chatbox.appendEcho("Unsupported genres are now enabled in Freeplay.")
    } else if (command == "/help") {
        chatbox.appendEcho(
            "These commands are used to cheat or work around generation errors. Use at your own risk:\n\n"+

            "/debugon - Enable debug mode\n"+
            "/debugoff - Disable debug mode\n"+
            "/delete_puzzle_data [num] - Delete save data for a specific puzzle\n"+
            "/set_puzzle_seed [num] [newParameters] - Overwrite the seed for a specific puzzle\n"+
            "/solve_collected - Auto-solve all puzzles whose locations have been checked\n"+
            "/show_unsupported - Display unfinished and unsupported genres in Freeplay"
        )
    } else {
        chatbox.appendEcho("Unknown command. Use /help to see available commands.")
    }
}

async function connectAP(hostname, port, player, password) {
    if (!client) {
        client = new Client();
        window.client = client;

        // TODO probably unnecessary to sync both due to ReceivedItems and RoomUpdate..?
        client.socket.on("receivedPacket", logEvent);
        client.socket.on("receivedItems", onReceiveItems);
        client.socket.on("roomUpdate", syncAPStatus);
        client.socket.on("setReply", onSetReply)
        client.socket.on("retrieved", onKeysRetreived)
        client.socket.on("disconnected", onDisconnected);

        client.messages.on("message", onMessage);
    }

    remoteSolved = {};

    console.log("connecting to AP...");

    const connectionInfo = {
        password: password ?? ""
    };

    let connectionURL = `${hostname}:${port}`
    const game = "sgtkeen"

    slotData = await client.login(connectionURL, player, game, connectionInfo);

    digitGroupCounts = slotData.digit_group_counts ?? [];

    console.log("connected to AP");

    syncAPStatus();
    
    const chatbox = Alpine.store("chatbox")
    chatbox.appendEcho("Connected to Archipelago.")
}

function isApReady() {
    return apReady && client.authenticated;
}

function initRemoteSolves() {
    let team = client.players.self.team
    let slot = client.players.self.slot
    let key = `sgtkeen_solves_${team}_${slot}`

    client.socket.send({cmd:"SetNotify", keys:[key]})
    client.socket.send({cmd:"Get", keys:[key]})
}

function itemIdToName(id) {
    return client.package.findPackage("sgtkeen").reverseItemTable[id]
}

function itemNameToId(name) {
    return client.package.findPackage("sgtkeen").itemTable[name]
}

function locationIdToName(id) {
    return client.package.findPackage("sgtkeen").reverseLocationTable[id]
}

function locationNameToId(name) {
    return client.package.findPackage("sgtkeen").locationTable[name]
}

function playerIdToName(id) {
    return client.players.slots[id].name
}

/**
 * 
 * @param {SaveData.GameSave} file
 */
function loadFileData(file, secretMode) {
    const puzzleList = Alpine.store("puzzleList");

    if (secretMode) {
        console.log("waow")
    }

    let isFreeplay = (file.id < 0);
    let showUnsupported = Alpine.store("debugLoader").showUnsupported;

    // TODO styling sometimes doesn't update when reconnecting while a puzzle is selected.
    // Seems like a bug with Alpine (or with how I'm using it), I'll probably have to switch to a different
    // UI/reactivity library
    puzzleList.entries = [];
    puzzleList.sortedEntries = [];
    puzzleList.selectPuzzle(null);
    puzzleList.solveTarget = file?.solveTarget ?? null;
    puzzleList.finished = file.finished;
    puzzleList.sortBySolved = !isFreeplay;

    for (let i = 0; i < file.puzzles.length; i++) {
        let options = {
            locked: file.puzzleLocked[i],
            solved: file.puzzleSolved[i],
            digitGroupCount: digitGroupCounts[i] ?? DEFAULT_DIGIT_GROUP_COUNT,
        }

        let newEntry;
        if (isFreeplay) {
            newEntry = ArchipelagoPuzzle.fromPuzzlesString(file.puzzles[i], null, i+1, options)

            if (!showUnsupported && ((genreInfo[newEntry.genre].hidden && !secretMode) || genreInfo[newEntry.genre].evenMoreHidden)) {
                // Skip hidden genres
                continue;
            }
        } else {
            newEntry = ArchipelagoPuzzle.fromArchipelagoString(file.puzzles[i], file.baseSeed, i+1, options)
        }

        puzzleList.entries.push(newEntry);
    }

    puzzleList.resort();
}

function disconnectAP() {
    const gamesaves = Alpine.store("gamesaves")
    apReady = false;
    gamesaves.connected = false;
    if (client && client.socket.connected) {
        console.log("disconnecting from AP...");
        client.socket.disconnect();
    }
}

// Expose UI functions to global scope
// I should probably move these to Alpine
window.showPreferences = showPreferences;
window.newPuzzle = newPuzzle;
window.puzzleFromId = puzzleFromId;
window.puzzleFromSeed = puzzleFromSeed;
window.restartPuzzle = restartPuzzle;
window.undoPuzzle = undoPuzzle;
window.redoPuzzle = redoPuzzle;
window.solvePuzzle = solvePuzzle;
window.setPreset = setPreset;
window.savePuzzleData = savePuzzleData;
window.loadPuzzleData = loadPuzzleData;
window.deletePuzzleData = deletePuzzleData;

// Expose some variables to global scope for ease of debugging
window.Alpine = Alpine;
window.store = Alpine.store;
window.client = client;
window.Client = Client;
window.ArchipelagoPuzzle = ArchipelagoPuzzle;
window.syncAPStatus = syncAPStatus;
window.SaveData = SaveData;
window.loadPuzzle = loadPuzzle;

Alpine.start();